### ISSUE TITLE
Zřízení subdatabáze dopisů Otokara Březiny

### ISSUE THREAD

**Issue by DanielaIwashita** [LIBCAS/hiko#140]
Prosíme o zřízení subdatabáze dopisů Otokara Březiny. Hlavní editorka bude Eliška Davidová, editorská práva by měla mít také Daniela Iwashita a Šárka Kořínková. Barbora Petrů, Eva Lauberová a František Bui by měli mít možnost vkládat a upravovat jednotlivé dopisy, ale do práce, kterou zadal někdo jiný, by měli mít možnost jen nahlížet, pokud to tak jde. Pokud ne, musejí mít také editační práva. Nahlížet může do databáze také Vladimír Urbánek a Tomáš Pavlíček.

**Comment by NikitaVrnv** [comment]
@DanielaIwashita 
Prosim o kontrolu:
https://brezina.historicka-korespondence.cz/

**Comment by DanielaIwashita** [comment]
Dobrý den, děkuji Vám mnohokrát, bohužel neznám přihlašovací heslo do databáze, můžete mi ho prosím dát?

**Comment by NikitaVrnv** [comment]
@DanielaIwashita, poslal jsem Vam odkaz pro nastaveni hesla. Prosim o kontrolu posty, ktera je uvedena v tabulce (Google Spreadsheets). Dekuji.

**Comment by NikitaVrnv** [comment]
Omlouvám se, @DanielaIwashita, to je způsobeno tím, že Váš e-mail (v pravém sloupci) je umístěn nad názvem databáze (v levém sloupci). E-mail Vám byl odeslán.

**Comment by DanielaIwashita** [comment]
Díky moc, do databáze jsme se už dostala, vypadá to v pořádku. Můžete prosím dát přístup i ostatním ze seznamu?

**Comment by NikitaVrnv** [comment]
Přidal jsem pana Kosáka. Kromě toho jsem přidal uživatele do databáze "Korespondence Jakuba Demla". Prosím, zkontrolujte, zda všichni 9 uživatelů získali přístup k oběma databázím. Moc děkuji, @DanielaIwashita

**Comment by DanielaIwashita** [comment]
Dobrý den, moc děkuji za všechno, všichni přístup k databázi potvrdili.

**Comment by NikitaVrnv** [comment]
Dobrý den, paní @DanielaIwashita,
Moc děkuji!
