### ISSUE TITLE
Překlopení dopisů ze zkušební databáze do subdatabáze Jakuba Demla

### ISSUE THREAD

**Issue by DanielaIwashita** [LIBCAS/hiko#142]
Prosíme o překlopení dopisů od Jakuba Demla (jako autora) a pro Jakuba Demla (jako) adresáta) obsažených ve zkušební databázi na linku https://historicka-korespondence.cz/hiko-v2/letters

Jde prakticky o všechny dopisy s výjimkou jednoho dopisu s ID 3 (autor Milada Blekastad), ID 4 (autor Komenský).

Děkuji

**Comment by DanielaIwashita** [comment]
Dobrý den, bohužel se mi stále nepodařilo se do databáze přihlásit, stále mi to hlásí chybu, i když si zadávám nové heslo

**Comment by DanielaIwashita** [comment]
Dobrý den, děkujeme, obsah nové databáze zkontroluje její hlavní editorka Šárka Kořínková a dá Vám zprávu, prosíme o strpení, dopisů je přes 300. A moc děkujeme za rychlou pomoc

**Comment by DanielaIwashita** [comment]
Dobrý den, Šárka Kořínková překlopení dat zkontrolovala a vše je podle ní v pořádku. Mnohokrát Vám děkujeme a tento požadavek uzavíráme. Daniela Iwashita

**Comment by NikitaVrnv** [comment]
Dobrý den, paní @DanielaIwashita ,
Děkuji Vám za kontrolu!
