### ISSUE TITLE
Nová osoba/instituce

### ISSUE THREAD

**Issue by martinovska** [LIBCAS/hiko#149]
Po vytvoření nové osoby/instituce se v případě Korespondence TGM (https://tgm.historicka-korespondence.cz/) tato osoba/instituce neukáže v nabídce při zadávání nového dopisu. V seznamu osob/institucí zobrazena je (Albert, Eduard), ale nelze ji zadat jako např. příjemce dopisu. Při zadávání nových míst je vše v pořádku, týká se tedy pravděpodobně pouze osob/institucí.

**Comment by NikitaVrnv** [comment]
<img width="760" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/24753cec-035f-47b3-827c-c2be628cfaed">

**Comment by NikitaVrnv** [comment]
Vazena pani @martinovska,

Jsem pridal osobu test,test. Viz screenshoty:
Zadny problem nevidim, bohuzel.

<img width="911" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/b5c3aecd-6289-4382-9220-d3c922d52914">
<img width="732" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/f30b0755-4c8d-427c-8789-e16993ed0c84">

S pozdravem,
Nikita Voronov
