### ISSUE TITLE
Front-end lang problem while looking for some place

### ISSUE THREAD

**Issue by NikitaVrnv** [LIBCAS/hiko#151]
Should be available for search on the front in any language based on the geonames.org.

**Comment by IvaLelka** [comment]
Dobrý den, jestli rozumím dobře tento problém se týká vyhledávání míst v jakémkoli jazyce. Dám-li ale vyhledávat origin nebo destination Praha, zdá se, že to nenajde nic? Stejně tak např. Lovaň atd.
Děkuji, Lelková

**Comment by NikitaVrnv** [comment]
Ano, přidal jsem štítek "duplicate" z důvodu toho, že jste přidala issue #171
