### ISSUE TITLE
Doplnění pole Další jména u Nové osoby/instituce

### ISSUE THREAD

**Issue by DanielaIwashita** [LIBCAS/hiko#165]
Na základě domluvy z online schůzky 19. 10. prosíme ve formuláři Nové osoby/instituce přidat pole Další jména.

**Comment by NikitaVrnv** [comment]
> U typu „Osoba“ potřebujeme dále možnost přidávat další jména (pseudonymy, vlastní jména, rodná příjmení žen apod.) – popis „Varianta jména“, a to libovolný počet; pro každé z těchto dalších jmen by měla být stejná tři pole (tj. pro hlavní a vedlejší jméno a obecný doplněk), jak je uvedeno výše...[]

**Comment by NikitaVrnv** [comment]
Dobry den, @DanielaIwashita,

prosim Vas o kontrolu. Dekuji!

**Comment by DanielaIwashita** [comment]
Dobrý den, 

mnohokrát Vám děkujeme za doplnění pole dalšího jména do databáze. 

Momentálně je se zadáváním dalších jmen jeden problém: pokud zadáváme novou osobu a její jméno společně s dalším jménem, nelze záznam uložit, místo toho se objeví chybová hláška: Eror 500, chyba serveru. 

Další jméno však lze přidat a uložit u jmen, která jsou již zadaná a uložená. 

Prosíme tedy ještě o odstranění tohoto problému a ještě jednou velký dík. 

Srdečně 

Daniela Iwashita 



[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS/hiko" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Pátek, 5. Leden 2024 13:09:09 
Předmět: Re: [LIBCAS/hiko] Doplnění pole Další jména u Nové osoby/instituce (Issue #165) 





Dobry den, [ https://github.com/DanielaIwashita | @DanielaIwashita ] , 

prosim Vas o kontrolu. Dekuji!

**Comment by NikitaVrnv** [comment]
Dobrý den, @DanielaIwashita,

Prosím o kontrolu. Děkuji.

**Comment by DanielaIwashita** [comment]
Dobrý den, 

také děkuji, už to funguje, díky! 

Srdečně 

Daniela I. 

[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS/hiko" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Čtvrtek, 11. Leden 2024 16:14:40 
Předmět: Re: [LIBCAS/hiko] Doplnění pole Další jména u Nové osoby/instituce (Issue #165) 





Dobrý den, [ https://github.com/DanielaIwashita | @DanielaIwashita ] , 

Prosím o kontrolu. Děkuji.
