### ISSUE TITLE
Přejmenování polí ve formuláři Nová osoba/instituce

### ISSUE THREAD

**Issue by DanielaIwashita** [LIBCAS/hiko#166]
Na základě domluvy z online schůzky 19. 10. prosíme ve formuláři Nové osoby/instituce přejmenovat tato pole:

Pole Příjmení prosíme přejmenovat na Příjmení / Hlavní část jména
Pole Rodné jméno prosíme přejmenovat na Rodné jméno / Vedlejší část jména,
Pole Profese prosíme přejmenovat na Role/profese.

Děkuji.

D. I.

**Comment by NikitaVrnv** [comment]
@DanielaIwashita, prosim o kontrolu. Dekuji.
<img width="1440" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/0f34ffb1-318b-4f63-ac36-ee8b3e400e69">
<img width="1440" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/301ffac8-6934-4dfd-96d9-267180f4779d">
