### ISSUE TITLE
V poli „Typ“ by měly být v roletce možnosti „Osoba/Rodina“ a „Instituce/Skupina“

### ISSUE THREAD

**Issue by NikitaVrnv** [LIBCAS/hiko#174]
<img width="810" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/2fe7fd1d-6551-4709-80c7-379084c627cc">

**Comment by NikitaVrnv** [comment]
@DanielaIwashita, prosim o kontrolu. 
Dekuji!

**Comment by DanielaIwashita** [comment]
Dobrý den, děkuji, formulář je opraven správně. 

Díky 

[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS/hiko" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Úterý, 12. Prosinec 2023 14:53:05 
Předmět: Re: [LIBCAS/hiko] V poli „Typ“ by měly být v roletce možnosti „Osoba/Rodina“ a „Instituce/Skupina“ (Issue #174) 





[ https://github.com/DanielaIwashita | @DanielaIwashita ] , prosim o kontrolu. 
Dekuji!
