### ISSUE TITLE
Muz/zena -> M/F (Deml) 

### ISSUE THREAD

**Issue by NikitaVrnv** [LIBCAS/hiko#183]
Replace in the database

**Comment by NikitaVrnv** [comment]
@DanielaIwashita, v korespondenci Demla jsem nahradil 'muž' na 'M' (396 řádků) a 'žena' na 'F' (73 řádků). Prosím o kontrolu. Děkuji!

**Comment by DanielaIwashita** [comment]
Dobrý den, děkujeme, je to perfektní, ušetřil jste nám práci. 

Daniela I. 

[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS/hiko" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Čtvrtek, 18. Leden 2024 15:06:56 
Předmět: Re: [LIBCAS/hiko] Muz/zena -> M/F (Deml) (Issue #183) 





[ https://github.com/DanielaIwashita | @DanielaIwashita ] , v korespondenci Demla jsem nahradil 'muž' na 'M' (396 řádků) a 'žena' na 'F' (73 řádků). Prosím o kontrolu. Děkuji!
