### ISSUE TITLE
Vytváření nových entit v dopisech - prolinky

### ISSUE THREAD

**Issue by DanielaIwashita** [LIBCAS/hiko#184]
Potřebujeme tlačítka s prolinky na vytváření nových entit (ve vyskakovacím okně nebo na nové kartě prohlížeče)
-          karta Nový dopis – 7 míst
o   Autor -> Nová osoba/instituce (tlačítko „Vytvořit novou entitu“ – všude?)
o   Příjemce -> Nová osoba/instituce
o   Místo odeslání -> Nové místo
o   Místo určení -> Nové místo
o   Klíčová slova -> Nové klíčové slovo
o   Zmíněné osoby -> Nová osoba/instituce
o   Manifestace a uložení -> Nové místo uložení

-          karta Lidé a instituce, typ osoba/rodina – 1 nebo 2 místa
o   Role/profese -> Nová profese
o   Kategorie profese -> Nová kategorie profese – jen pokud by se nenačítala automaticky podle zvolené profese (viz další stranu)

-           karta Klíčová slova – 1 místo
o   Kategorie -> Nová kategorie klíčových slov

-          karta Role/profese – 0 nebo 1 místo
o   Kategorie -> Nová kategorie role/profese – momentálně tady to pole není, ale navrhujeme ho

-          celkem bychom chtěli vytvořit 10 prolinků na 4 kartách

**Comment by NikitaVrnv** [comment]
Vážená paní @DanielaIwashita,

zkontrolujte prosím funkčnost prolinku. Děkuji

S pozdravem,
Nikita
