### ISSUE TITLE
"Vytvořit novou osobu/instituci" ve formuláři dopisu

### ISSUE THREAD

**Issue by SarkaKorinkova** [LIBCAS/hiko#187]
Nikito, prosím o vytvoření vyskakovacího okna ve formuláři dopisu (Dopis - Nový dopis) pod políčkem "Zmíněné osoby/instituce", je to stejná funkce jako u klíčového slova. Popis: Vytvořit novou osobu/instituci". 

Děkuji.
Šárka

**Comment by DanielaIwashita** [comment]
Tato funkce je už u pole Jméno autora a  Jméno příjemce, ale problém je s pojmenováním toho linku, teď je tam v obou případech napsáno "Vytvořit novou entitu". Prosím, aby byl ten prolink místo toho nazván (přejmenován) také "Vytvořit novou osobu/instituci" 

Pak to bude srozumitelnější.

Moc děkuji

Daniela

**Comment by NikitaVrnv** [comment]
Ahoj @SarkaKorinkova a @DanielaIwashita, 

nahral jsem zmeny na produkci, prosim o kontrolu.

Dekuji :)

Nikita

**Comment by DanielaIwashita** [comment]
Milý Nikito, 

díky za mě perfektní. 

Daniela 

[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Čtvrtek, 23. Květen 2024 00:07:16 
Předmět: Re: [LIBCAS/hiko] "Vytvořit novou osobu/instituci" ve formuláři dopisu (Issue #187) 





Ahoj [ https://github.com/SarkaKorinkova | @SarkaKorinkova ] a [ https://github.com/DanielaIwashita | @DanielaIwashita ] , 

nahral jsem zmeny na produkci, prosim o kontrolu. 

Dekuji :) 

Nikita
