### ISSUE TITLE
Nová role editora s omezením mazat jakákoli data

### ISSUE THREAD

**Issue by NikitaVrnv** [LIBCAS/hiko#188]
> Potřebujeme zřídit omezený editační přístup k databázi Deml a Březina pro tři nové kolegyně, které začnou od června zadávat do databáze dopisy. 
> 
> Omezený editační přístup si představujeme tak, že budou moci do databáze něco přidávat, ale neměly by v ní mazat.

**Comment by NikitaVrnv** [comment]
Ahoj @DanielaIwashita,

pridal novou roli a zalozil ucty. 

Prosim o kontrolu. Dekuji!

Viz: 

+ New editor's role (contributor) with a restriction from deleting any data (https://github.com/LIBCAS/hiko/issues/188)
+ Security update (https://github.com/LIBCAS/hiko/issues/189)
+ New data display in the admin panel (https://github.com/LIBCAS/hiko/issues/190) for: keywords (/keywords/{id}/edit), keyword categories (/keywords/category/{id}/edit), professions (/professions/{id}/edit), profession categories (/professions/category/{id}/edit);
+ Small changes, bug fixes.

<img width="839" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/d3374248-1837-471a-af72-43dc3f76b8c1">

Nikita

**Comment by SarkaKorinkova** [comment]
Milý Nikito,

otestovala jsem nový účet sarka.korinkova@ucl.cas.cz v databázi Březina a omezení funguje, můžu jen vytvářet a upravovat, ale nemůžu nic smazat. Ale v databázi Deml jsem na svém klasickém gmailu (sarka.korinkova@gmail.com) přišla také o oprávnění mazat data. Mohl bys mi ten přístup vrátit?

Díky.
Šárka

**Comment by NikitaVrnv** [comment]
> Milý Nikito,
> 
> otestovala jsem nový účet [sarka.korinkova@ucl.cas.cz](mailto:sarka.korinkova@ucl.cas.cz) v databázi Březina a omezení funguje, můžu jen vytvářet a upravovat, ale nemůžu nic smazat. Ale v databázi Deml jsem na svém klasickém gmailu ([sarka.korinkova@gmail.com](mailto:sarka.korinkova@gmail.com)) přišla také o oprávnění mazat data. Mohl bys mi ten přístup vrátit?
> 
> Díky. Šárka

Milá Šárko,

pro ověření funkčnosti jsem omezil přístup (editor->contributor) ke dvěma databázím, nyní jsem vrátil původní nastavení. 

Děkuji za kontrolu :)
Nikita

**Comment by NikitaVrnv** [comment]
> děkuju za ten přístup, už mi opět funguje vše.
> 
> Za náš tým jsem se chtěla zeptat, jak to vypadá s kategoriemi profesí, kdy to plánuješ propojit s profesemi v databázi.
> 
> A pak mám otázku za Adélu Junovou Mackovou, ptala se, kdy bude možné slučovat profese. Má několik podobných a potřebovala by je sloučit, než dojde k tomu napojení kategorií profesí. Ale pokud by to nešlo, nějak by si s tím poradila i potom.


Milá @SarkaKorinkova,

Děkuji Tě za odpověď,

momentálně pracuji na vyhledávání duplicitních dopisu ve stejné databázi a také v jiných databázích s použitím různých algoritmů a datových sad (snímek obrazovky). Jakmile bude tento složitý úkol dokončen, začnu pracovat na výše uvedených úkolech. 

Děkuji,
Nikita

<img width="1361" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/cb055835-6eb8-463a-b2e2-d4aad1c851d1">
