### ISSUE TITLE
Přidávání fulltextu 

### ISSUE THREAD

**Issue by IvaLelka** [LIBCAS/hiko#191]
Dobrý den, nedaří se mi přidávat fulltext do databáze Polanus. Mohl byste se na to podívat? Díky, Iva L.

**Comment by NikitaVrnv** [comment]
Dobrý den, paní Lelková,

děkuji Vám za testování a objevení tohoto problému. Opravil jsem chybu a nahrávám soubory na server, protože jsem aktualizoval závislosti a zároveň odstranil konflikt. Během 15-20 minut bude editor opět plně funkční.

Zítra bude připraveno k testování hledání podobných dopisů mezi databázemi pomocí Jaccardova indexu. Byl bych Vám velmi vděčný, kdybyste poskytla zpětnou vazbu k novému funkcionalitě. Vám objeví nová položka v menu "Duplikáty" v administrátorské panelu HIKO.

Omlouvám se, že jsem nereagoval na vytvořené issue dříve, protože upozornění na tento repozitář nebyla zapnutá při vytvoření nových issues, tedy v případě, že jsem nebyl uveden ve zprávě.

Děkuji za pochopení a spolupráci.

S pozdravem,
Nikita Voronov

**Comment by NikitaVrnv** [comment]
<img width="1102" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/f299dca6-58b9-4d5f-8aed-9e874c1f2224">
@IvaLelka

**Comment by NikitaVrnv** [comment]
<img width="154" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/d91db3cc-ec86-49a9-8a8c-fb4346327067">
