### ISSUE TITLE
Undefined index: label fix (/resources/views/livewire/letter-meta-field.blade.php)

### ISSUE THREAD

**Issue by NikitaVrnv** [LIBCAS/hiko#193]
<img width="767" alt="image" src="https://github.com/LIBCAS/hiko/assets/90269610/5edffe94-2298-40a7-a07b-40f0c1be8d9e">

**Comment by NikitaVrnv** [comment]
@DanielaIwashita, prosim o kontrolu

**Comment by DanielaIwashita** [comment]
Díky, kolegyně to zkontroluje. 

D 

[ http://www.ucl.cas.cz/ |    ] 	
Mgr. Daniela Iwashita, Ph.D. 
oddělení ediční a textologické 
vedoucí týmu pro výzkum korespondence Jakuba Demla 
department of scholarly editing 
head of the Jakub Deml’s letters research group 
Ústav pro českou literaturu AV ČR, v.v.i. 
Institute of Czech Literature of the CAS 
Na Florenci 1420/3, 110 00 Praha 1, Czech Republic 
T +420 222 828 209 
E [ ***@***.*** | ***@***.*** ] 
W [ http://www.ucl.cas.cz/ | www.ucl.cas.cz ] 


Od: "Nikita Voronov" ***@***.***> 
Komu: "LIBCAS" ***@***.***> 
Kopie: "Daniela Iwashita" ***@***.***>, "Mention" ***@***.***> 
Odeslané: Úterý, 18. Červen 2024 13:47:25 
Předmět: Re: [LIBCAS/hiko] Undefined index: label fix (/resources/views/livewire/letter-meta-field.blade.php) (Issue #193) 





[ https://github.com/DanielaIwashita | @DanielaIwashita ] , prosim o kontrolu

**Comment by NikitaVrnv** [comment]
> databáze funguje správně, můžeš toto Issue považovat za uzavřené
